services:
  - type: web
    name: capstone-backend
    env: python
    buildCommand: ""
    startCommand: python app.py
    plan: free
    autoDeploy: true

services:
  - type: web
    name: capstone-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: SUPABASE_URL
        value: https://nfcgehfenpjqrijxgzio.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mY2dlaGZlbnBqcXJpanhnemlvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDc0Mjk4MSwiZXhwIjoyMDY2MzE4OTgxfQ.B__RkNBjBlRn9QC7L72lL2wZKO7O3Yy2iM-Da1cllpc

FROM python:3.11

# Install system dependencies
RUN apt-get update && apt-get install -y poppler-utils

# Set working directory
WORKDIR /app

# Copy and install Python dependencies
COPY . .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python", "app.py"]
